### ISSUE TITLE
github-clone fails due to https redirection

### ISSUE THREAD

**Issue by AlisterH** [Narnach/github-clone#2]
Hi, I'm not sure if you're interested, as you're obviously not actively working on it, but it doesn't seem to work anymore:

````
#   github-clone DeforaOS
/usr/lib/ruby/1.9.1/open-uri.rb:216:in `open_loop': redirection forbidden: http://github.com/api/v1/yaml/DeforaOS -> https://github.com/api/v1/yaml/DeforaOS (RuntimeError)
        from /usr/lib/ruby/1.9.1/open-uri.rb:146:in `open_uri'
        from /usr/lib/ruby/1.9.1/open-uri.rb:677:in `open'
        from /usr/lib/ruby/1.9.1/open-uri.rb:33:in `open'
        from /usr/local/bin/github-clone:47:in `raw_yaml'
        from /usr/local/bin/github-clone:52:in `data'
        from /usr/local/bin/github-clone:57:in `repositories'
        from /usr/local/bin/github-clone:63:in `clone_repositories'
        from /usr/local/bin/github-clone:18:in `clone_new_repositories'
        from /usr/local/bin/github-clone:122:in `<main>'

**Comment by Narnach** [comment]
Hey! It has indeed been a long time since I last used this myself. The code was written when Ruby 1.8.7 was the "current" version, and when HTTPS cost at least €500/year. The error looks familiar; `open-uri` is not quite fond of redirects. Let me have a look to see if I can fix this :)

**Comment by Narnach** [comment]
Digging a little deeper I discovered the root cause was that I was using the v1 API of Github, which has been removed years ago. I've updated github-clone to use the new v3 API, and to support OAuth token login (see readme) so you can now also clone private repos, organization repos, etc.
